temp_dir: /tmp/fisherman/
shell_pipe: /tmp/fisherman/cmdpipe
update_frequency: 0 # ms between each batch of updates sent to server
max_cmds_per_update: 1
host_url: http://localhost:4000
user:
  email: foo.foo@gmail.com
  username: foo.bar
  first_name: henry
  last_name: warren
  machine_serial: xyz
